<a href="https://colab.research.google.com/github/keerthh129/AIML-Colab/blob/main/Decision_tree_Heart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [8]:
df = pd.read_csv('Heart rate.csv')

print(df.head())
print(df.columns)

   HeartRate     HRV  Age  Gender Activity  BodyTemperature StressLevel  \
0         98   79.89   36    Male  Walking            37.78      Medium   
1        111   89.48   45  Female  Walking            36.50        High   
2         88  108.05   43  Female  Walking            37.84         Low   
3         74   82.44   54    Male  Walking            37.32      Medium   
4        102   49.56   43    Male  Walking            37.77         Low   

   Emotion  
0     fear  
1    angry  
2    happy  
3  neutral  
4     fear  
Index(['HeartRate', 'HRV', 'Age', 'Gender', 'Activity', 'BodyTemperature',
       'StressLevel', 'Emotion'],
      dtype='object')


In [9]:
df = df.dropna()

In [10]:
le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

In [13]:
X = df.drop('Emotion', axis=1)
y = df['Emotion']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [15]:
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [5, 10, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid = GridSearchCV(
    DecisionTreeClassifier(random_state=42),
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train, y_train)

best_model = grid.best_estimator_

print("Best Parameters:", grid.best_params_)

Best Parameters: {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 1, 'min_samples_split': 2}


In [16]:
y_pred = best_model.predict(X_test)

In [17]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         6
           3       1.00      1.00      1.00        12
           4       1.00      1.00      1.00         7

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40


Confusion Matrix:
 [[ 3  0  0  0  0]
 [ 0 12  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0 12  0]
 [ 0  0  0  0  7]]


In [18]:
cv_scores = cross_val_score(best_model, X, y, cv=5)
print("Cross-validation Accuracy:", np.mean(cv_scores))

Cross-validation Accuracy: 1.0
